import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'ar' || saved === 'en') ? saved : 'en';
  });

  const isRTL = language === 'ar';

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];

    for (const k of keys) {
      if (value && typeof value === 'object') {
        value = value[k];
      } else {
        return key;
      }
    }

    return typeof value === 'string' ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations: Record<Language, any> = {
  en: {
    common: {
      loading: 'Loading...',
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      view: 'View',
      search: 'Search',
      filter: 'Filter',
      logout: 'Logout',
      login: 'Login',
      register: 'Register',
      submit: 'Submit',
      back: 'Back',
      next: 'Next',
      close: 'Close',
      confirm: 'Confirm',
      yes: 'Yes',
      no: 'No',
      support: '24/7 Support',
      addNew: 'Add New',
      actions: 'Actions',
      status: 'Status',
      active: 'Active',
      inactive: 'Inactive',
      pending: 'Pending',
      approved: 'Approved',
      rejected: 'Rejected',
      all: 'All',
      total: 'Total',
      details: 'Details',
      download: 'Download',
      upload: 'Upload',
      send: 'Send',
      receive: 'Receive',
      success: 'Success',
      error: 'Error',
      warning: 'Warning',
      info: 'Info',
      refresh: 'Refresh',
      update: 'Update',
      create: 'Create',
      remove: 'Remove',
    },
    landing: {
      title: 'AutoSupport Pro',
      subtitle: 'Professional Automotive Service Management',
      description: 'Streamline your automotive service operations with our comprehensive support platform',
      getStarted: 'Get Started',
      features: 'Our Features',
      whyChooseUs: 'Why Choose Us',
      realTimeDiagnostics: 'Real-time Diagnostics',
      expertSupport: 'Expert Support',
      comprehensiveReporting: 'Comprehensive Reporting',
      liveDiagnostics: 'Live Diagnostics',
      scanningSystem: 'Scanning systems...',
      trustedBy: 'Trusted by 10,000+ Vehicle Owners',
      yourCarHealth: "Your Car's Health Deserves Attention, Just Like Your Own",
      carDocDescription: 'With CarDoc and AutoDoc subscriptions, you own the car — we take care of it. Weekly or bi-weekly precision inspections that save you thousands at the garage.',
      reviews: 'reviews',
      resolution: 'Resolution',
      viewPlans: 'View Subscription Plans',
      talkToExpert: 'Talk to Expert',
      subscriptionPlans: 'Subscription Plans',
      whySubscribe: 'Why Subscribe?',
      preventiveCare: 'Preventive Care',
      preventiveDesc: 'Regular inspections catch problems before they become expensive repairs',
      expertTechnicians: 'Expert Technicians',
      expertDesc: 'Certified professionals with years of automotive experience',
      detailedReports: 'Detailed Reports',
      detailedDesc: 'Comprehensive digital reports after every inspection',
      prioritySupport: 'Priority Support',
      priorityDesc: '24/7 dedicated support line for all subscribers',
      moneyBackGuarantee: 'Money-Back Guarantee',
      guaranteeDesc: 'Not satisfied? Get a full refund within 30 days',
      flexibleScheduling: 'Flexible Scheduling',
      schedulingDesc: 'Book inspections at your convenience',
      howItWorks: 'How It Works',
      step1: 'Choose Your Plan',
      step1Desc: 'Select weekly or bi-weekly inspections',
      step2: 'Schedule Visit',
      step2Desc: 'Pick a convenient time for technician visit',
      step3: 'Expert Inspection',
      step3Desc: 'Certified technician performs thorough check',
      step4: 'Get Report',
      step4Desc: 'Receive detailed digital inspection report',
      readyToStart: 'Ready to Start Protecting Your Vehicle?',
      joinThousands: 'Join thousands of satisfied customers who trust us with their vehicles',
      getStartedToday: 'Get Started Today',
      backToHome: 'Back to Home',
      noCreditCard: 'No credit card required',
      cancelAnytime: 'Cancel anytime',
      or: 'or',
      whyCarDocSaves: 'Why CarDoc & AutoDoc Saves You Money',
      preventativeMaintenance: 'Preventative maintenance that keeps your car on the road, not in the garage',
      scheduledVisits: 'Scheduled Visits',
      scheduledVisitsDesc: 'Weekly or bi-weekly precision inspections at your location',
      regularCheckups: 'Regular checkups',
      completeDiagnostics: 'Complete Diagnostics',
      completeDiagnosticsDesc: 'Engine, transmission, A/C, electrical, brakes, and every system',
      fullInspection: 'Full inspection',
      detailedReportsTitle: 'Detailed Reports',
      detailedReportsDesc: 'Get comprehensive reports after every inspection for your records',
      completeHistory: 'Complete history',
      saveThousands: 'Save Thousands',
      saveThousandsDesc: 'Proper diagnosis prevents unnecessary part replacements at garages',
      costTracking: 'Cost tracking',
      needUrgentSupport: 'Need Urgent Support?',
      urgentSupportDesc: 'All subscribers get access to our 24/7 emergency support system. You can also create support tickets anytime for immediate assistance.',
      contactSupport: 'Contact Support',
      readyToTransform: 'Ready to Transform Your Car Care Experience?',
      joinSatisfied: 'Join 10,000+ satisfied vehicle owners who trust AutoSupport Pro for their automotive needs',
      startFreeToday: 'Start Free Today',
      scheduleDemo: 'Schedule a Demo',
      expertSupport24_7: '24/7 expert support',
      activeUsers: 'Active Users',
      issuesResolved: 'Issues Resolved',
      averageRating: 'Average Rating',
      whatCustomersSay: 'What Our Customers Say',
      realFeedback: 'Real feedback from real car owners',
    },
    auth: {
      welcomeBack: 'Welcome Back',
      createAccount: 'Create Account',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      fullName: 'Full Name',
      phoneNumber: 'Phone Number',
      signIn: 'Sign In',
      signUp: 'Sign Up',
      dontHaveAccount: "Don't have an account?",
      alreadyHaveAccount: 'Already have an account?',
      signInHere: 'Sign in here',
      signUpHere: 'Sign up here',
      or: 'or',
      signingIn: 'Signing in...',
      creatingAccount: 'Creating account...',
    },
    dashboard: {
      welcome: 'Welcome',
      dashboard: 'Dashboard',
      tickets: 'Tickets',
      customers: 'Customers',
      technicians: 'Technicians',
      inventory: 'Inventory',
      reports: 'Reports',
      settings: 'Settings',
      management: 'Management',
      profile: 'Profile',
      subscriptions: 'Subscriptions',
      vehicles: 'Vehicles',
      visits: 'Visits',
      payments: 'Payments',
      notifications: 'Notifications',
      myAccount: 'My Account',
      serviceHistory: 'Service History',
      upcomingVisits: 'Upcoming Visits',
      recentActivity: 'Recent Activity',
      statistics: 'Statistics',
      overview: 'Overview',
    },
    ticket: {
      title: 'Title',
      status: 'Status',
      priority: 'Priority',
      description: 'Description',
      assignedTo: 'Assigned To',
      createdAt: 'Created At',
      updatedAt: 'Updated At',
      open: 'Open',
      inProgress: 'In Progress',
      resolved: 'Resolved',
      closed: 'Closed',
      low: 'Low',
      medium: 'Medium',
      high: 'High',
      urgent: 'Urgent',
    },
    customer: {
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      vehicles: 'Vehicles',
      serviceHistory: 'Service History',
      vipTier: 'VIP Tier',
    },
    customerDashboard: {
      dashboard: 'Dashboard',
      manageTickets: 'Manage your support tickets and subscriptions',
      subscribeNow: 'Subscribe Now',
      getRegularMaintenance: 'Get Regular Car Maintenance with CarDoc or AutoDoc',
      subscribeWeekly: 'Subscribe to weekly or bi-weekly precision inspections. Save thousands through proper diagnostics.',
      carDocFor1Car: 'CarDoc for 1 car',
      autoDocFor2to3Cars: 'AutoDoc for 2-3 cars',
      exploreSubscriptions: 'Explore Subscriptions',
      viewMySubscription: 'View My Subscription',
      viewSubscriptionVisits: 'View Subscription & Visits',
      myTickets: 'My Tickets',
      noTicketsYet: 'No support tickets yet',
      createFirstTicket: 'Create your first ticket to get help from our technicians',
      createTicket: 'Create Ticket',
      serviceHistory: 'Service History',
      viewAllHistory: 'View All History',
      myInvoices: 'My Invoices',
      viewAllInvoices: 'View All Invoices',
      customizeDashboard: 'Customize Dashboard',
      switchToLightMode: 'Switch to light mode',
      switchToDarkMode: 'Switch to dark mode',
      newTicket: 'New Support Ticket',
      ticketTitle: 'Ticket Title',
      briefDescription: 'Brief description of the problem',
      vehicleInfo: 'Vehicle Information',
      vehicleMake: 'Vehicle Make',
      vehicleModel: 'Vehicle Model',
      makeExample: 'Toyota, Ford, BMW, etc.',
      modelExample: 'Camry, F-150, X5, etc.',
      vehicleYear: 'Vehicle Year',
      serviceType: 'Service Type',
      serviceExample: 'Oil change, brake repair, etc.',
      problemDescription: 'Problem Description',
      describeProblem: 'Describe the problem in detail...',
      attachments: 'Attachments (optional)',
      dragAndDrop: 'Drag and drop files here, or click to select',
      clickToUpload: 'Click to upload',
      creating: 'Creating...',
      cancel: 'Cancel',
      invoiceDetails: 'Invoice Details',
      ticketDetails: 'Ticket Details',
      vehicle: 'Vehicle',
      year: 'Year',
      technician: 'Technician',
      notAssignedYet: 'Not assigned yet',
      estimatedCost: 'Estimated Cost',
      paymentStatus: 'Payment Status',
      messages: 'Messages',
      typeMessage: 'Type your message...',
      send: 'Send',
      sending: 'Sending...',
      close: 'Close',
      paid: 'Paid',
      pending: 'Pending',
      unpaid: 'Unpaid',
      open: 'Open',
      inProgress: 'In Progress',
      awaitingPayment: 'Awaiting Payment',
      resolved: 'Resolved',
      closed: 'Closed',
    },
    subscription: {
      plans: 'Subscription Plans',
      carDoc: 'CarDoc',
      autoDoc: 'AutoDoc',
      weekly: 'Weekly',
      biWeekly: 'Bi-Weekly',
      perMonth: 'per month',
      subscribe: 'Subscribe Now',
      mostPopular: 'Most Popular',
      bestValue: 'Best Value',
      includes: 'Includes',
      inspection: 'Inspection',
      report: 'Detailed Report',
      support: 'Priority Support',
      warranty: 'Service Warranty',
      discount: 'Discount on Repairs',
      active: 'Active',
      expired: 'Expired',
      canceled: 'Canceled',
      renewOn: 'Renews on',
      expiresOn: 'Expires on',
      canceledOn: 'Canceled on',
      chooseYourPlan: 'Choose Your Car Care Plan',
      subscribeToCarDoc: 'Subscribe to',
      andLetExperts: 'and let our expert technicians keep your car in perfect health',
      monthly: 'Monthly',
      yearly: 'Yearly',
      save10: 'Save 10%',
      oneCar: '1 CAR',
      twoCars: '2-3 CARS',
      premium: 'PREMIUM',
      xPerWeek: '1x/week',
      visits: 'visits',
      visitsPerCar: 'visits/car',
      visitsMo: 'visits/mo',
      oneVehicle: 'ONE vehicle • 1x or 2x/week',
      complete12System: 'Complete 12-system checkup',
      reportsTracking: 'Reports & cost tracking',
      support24_7: '24/7 support',
      upTo3Vehicles: 'Up to 3 vehicles',
      priorityScheduling: 'Priority scheduling',
      advancedDiagnostics: 'Advanced diagnostics',
      fleetDashboard: 'Fleet dashboard & VIP support',
      yearlySave: 'Yearly: Save 10%',
      getCarDoc: 'Get CarDoc',
      getAutoDoc: 'Get AutoDoc',
      howItWorks: 'How CarDoc & AutoDoc Work',
      subscribeStep: 'Subscribe',
      subscribeStepDesc: 'Choose your plan and schedule your first visit',
      weVisitYou: 'We Visit You',
      weVisitYouDesc: 'Our technician conducts a complete precision checkup at your location',
      getReport: 'Get Report',
      getReportDesc: 'Receive detailed findings and recommendations instantly',
      addVehicles: 'Add Your Vehicles',
      selected: 'Selected',
      vehicle: 'Vehicle',
      makePlaceholder: 'Toyota, BMW, etc.',
      modelPlaceholder: 'Camry, X5, etc.',
      optional: 'Optional',
      addAnotherVehicle: 'Add Another Vehicle',
      backToPlans: 'Back to Plans',
      activating: 'Activating...',
      activateSubscription: 'Activate Subscription',
      selectSubscription: 'Select the subscription that fits your needs',
      carDocPlans: 'CarDoc Plans (1 Vehicle)',
      autoDocPlans: 'AutoDoc Plans (2-3 Vehicles)',
      carOnly: 'CAR ONLY 1',
      perYear: '/year',
      selectPlan: 'Select Plan',
      selectPremiumPlan: 'Select Premium Plan',
      support24_7Included: 'support included 24/7',
    },
    payment: {
      amount: 'Amount',
      date: 'Date',
      method: 'Payment Method',
      status: 'Status',
      paid: 'Paid',
      pending: 'Pending',
      failed: 'Failed',
      cash: 'Cash',
      card: 'Card',
      bankTransfer: 'Bank Transfer',
      receipt: 'Receipt',
      invoice: 'Invoice',
      total: 'Total',
      subtotal: 'Subtotal',
      tax: 'Tax',
      discount: 'Discount',
    },
    vehicle: {
      make: 'Make',
      model: 'Model',
      year: 'Year',
      vin: 'VIN',
      plateNumber: 'Plate Number',
      mileage: 'Mileage',
      color: 'Color',
      fuelType: 'Fuel Type',
      transmission: 'Transmission',
      addVehicle: 'Add Vehicle',
      editVehicle: 'Edit Vehicle',
      deleteVehicle: 'Delete Vehicle',
    },
    visit: {
      scheduled: 'Scheduled',
      completed: 'Completed',
      cancelled: 'Cancelled',
      inProgress: 'In Progress',
      scheduledFor: 'Scheduled For',
      completedOn: 'Completed On',
      technician: 'Technician',
      notes: 'Notes',
      report: 'Report',
      viewDetails: 'View Details',
      reschedule: 'Reschedule',
      cancel: 'Cancel Visit',
    },
  },
  ar: {
    common: {
      loading: 'جاري التحميل...',
      save: 'حفظ',
      cancel: 'إلغاء',
      delete: 'حذف',
      edit: 'تعديل',
      view: 'عرض',
      search: 'بحث',
      filter: 'تصفية',
      logout: 'تسجيل الخروج',
      login: 'تسجيل الدخول',
      register: 'التسجيل',
      submit: 'إرسال',
      back: 'رجوع',
      next: 'التالي',
      close: 'إغلاق',
      confirm: 'تأكيد',
      yes: 'نعم',
      no: 'لا',
      support: 'دعم 24/7',
      addNew: 'إضافة جديد',
      actions: 'الإجراءات',
      status: 'الحالة',
      active: 'نشط',
      inactive: 'غير نشط',
      pending: 'قيد الانتظار',
      approved: 'موافق عليه',
      rejected: 'مرفوض',
      all: 'الكل',
      total: 'المجموع',
      details: 'التفاصيل',
      download: 'تحميل',
      upload: 'رفع',
      send: 'إرسال',
      receive: 'استلام',
      success: 'نجاح',
      error: 'خطأ',
      warning: 'تحذير',
      info: 'معلومات',
      refresh: 'تحديث',
      update: 'تحديث',
      create: 'إنشاء',
      remove: 'إزالة',
    },
    landing: {
      title: 'أوتو سبورت برو',
      subtitle: 'إدارة خدمات السيارات الاحترافية',
      description: 'قم بتبسيط عمليات خدمة السيارات الخاصة بك من خلال منصة الدعم الشاملة لدينا',
      getStarted: 'ابدأ الآن',
      features: 'ميزاتنا',
      whyChooseUs: 'لماذا تختارنا',
      realTimeDiagnostics: 'التشخيص في الوقت الفعلي',
      expertSupport: 'دعم الخبراء',
      comprehensiveReporting: 'تقارير شاملة',
      liveDiagnostics: 'التشخيص المباشر',
      scanningSystem: 'فحص الأنظمة...',
      trustedBy: 'موثوق به من قبل أكثر من 10,000 مالك سيارة',
      yourCarHealth: 'صحة سيارتك تستحق الاهتمام، تماماً كصحتك',
      carDocDescription: 'مع اشتراكات كاردوك وأوتودوك، أنت تملك السيارة - ونحن نعتني بها. فحوصات دقيقة أسبوعية أو نصف أسبوعية توفر عليك الآلاف في الورشة.',
      reviews: 'تقييم',
      resolution: 'الحلول',
      viewPlans: 'عرض خطط الاشتراك',
      talkToExpert: 'تحدث مع خبير',
      subscriptionPlans: 'خطط الاشتراك',
      whySubscribe: 'لماذا الاشتراك؟',
      preventiveCare: 'الرعاية الوقائية',
      preventiveDesc: 'الفحوصات المنتظمة تكتشف المشاكل قبل أن تصبح إصلاحات باهظة الثمن',
      expertTechnicians: 'فنيون خبراء',
      expertDesc: 'محترفون معتمدون بسنوات من الخبرة في مجال السيارات',
      detailedReports: 'تقارير مفصلة',
      detailedDesc: 'تقارير رقمية شاملة بعد كل فحص',
      prioritySupport: 'دعم ذو أولوية',
      priorityDesc: 'خط دعم مخصص على مدار الساعة لجميع المشتركين',
      moneyBackGuarantee: 'ضمان استرداد الأموال',
      guaranteeDesc: 'غير راضٍ؟ احصل على استرداد كامل خلال 30 يوماً',
      flexibleScheduling: 'جدولة مرنة',
      schedulingDesc: 'احجز الفحوصات في الوقت المناسب لك',
      howItWorks: 'كيف يعمل',
      step1: 'اختر خطتك',
      step1Desc: 'حدد فحوصات أسبوعية أو نصف أسبوعية',
      step2: 'جدول الزيارة',
      step2Desc: 'اختر وقتاً مناسباً لزيارة الفني',
      step3: 'فحص الخبراء',
      step3Desc: 'فني معتمد يقوم بفحص شامل',
      step4: 'احصل على التقرير',
      step4Desc: 'استلم تقرير فحص رقمي مفصل',
      readyToStart: 'هل أنت مستعد لبدء حماية سيارتك؟',
      joinThousands: 'انضم إلى آلاف العملاء الراضين الذين يثقون بنا في سياراتهم',
      getStartedToday: 'ابدأ اليوم',
      backToHome: 'العودة للصفحة الرئيسية',
      noCreditCard: 'لا حاجة لبطاقة ائتمان',
      cancelAnytime: 'الإلغاء في أي وقت',
      or: 'أو',
      whyCarDocSaves: 'لماذا كاردوك وأوتودوك توفر لك المال',
      preventativeMaintenance: 'الصيانة الوقائية التي تبقي سيارتك على الطريق، وليس في الورشة',
      scheduledVisits: 'زيارات مجدولة',
      scheduledVisitsDesc: 'فحوصات دقيقة أسبوعية أو نصف أسبوعية في موقعك',
      regularCheckups: 'فحوصات منتظمة',
      completeDiagnostics: 'تشخيص كامل',
      completeDiagnosticsDesc: 'المحرك، ناقل الحركة، المكيف، الكهرباء، الفرامل، وكل نظام',
      fullInspection: 'فحص شامل',
      detailedReportsTitle: 'تقارير مفصلة',
      detailedReportsDesc: 'احصل على تقارير شاملة بعد كل فحص لسجلاتك',
      completeHistory: 'سجل كامل',
      saveThousands: 'وفر الآلاف',
      saveThousandsDesc: 'التشخيص الصحيح يمنع استبدال القطع غير الضرورية في الورش',
      costTracking: 'تتبع التكاليف',
      needUrgentSupport: 'هل تحتاج إلى دعم عاجل؟',
      urgentSupportDesc: 'جميع المشتركين يحصلون على وصول إلى نظام الدعم الطارئ على مدار 24/7. يمكنك أيضاً إنشاء تذاكر دعم في أي وقت للحصول على المساعدة الفورية.',
      contactSupport: 'اتصل بالدعم',
      readyToTransform: 'هل أنت مستعد لتحويل تجربة العناية بسيارتك؟',
      joinSatisfied: 'انضم إلى أكثر من 10,000 مالك سيارة راضٍ يثقون في AutoSupport Pro لاحتياجاتهم من السيارات',
      startFreeToday: 'ابدأ مجاناً اليوم',
      scheduleDemo: 'حجز عرض توضيحي',
      expertSupport24_7: 'دعم خبراء 24/7',
      activeUsers: 'مستخدمون نشطون',
      issuesResolved: 'مشاكل تم حلها',
      averageRating: 'متوسط التقييم',
      whatCustomersSay: 'ماذا يقول عملاؤنا',
      realFeedback: 'تعليقات حقيقية من أصحاب سيارات حقيقيين',
    },
    auth: {
      welcomeBack: 'مرحبا بعودتك',
      createAccount: 'إنشاء حساب',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      confirmPassword: 'تأكيد كلمة المرور',
      fullName: 'الاسم الكامل',
      phoneNumber: 'رقم الهاتف',
      signIn: 'تسجيل الدخول',
      signUp: 'إنشاء حساب',
      dontHaveAccount: 'ليس لديك حساب؟',
      alreadyHaveAccount: 'هل لديك حساب بالفعل؟',
      signInHere: 'سجل الدخول هنا',
      signUpHere: 'سجل هنا',
      or: 'أو',
      signingIn: 'جاري تسجيل الدخول...',
      creatingAccount: 'جاري إنشاء الحساب...',
    },
    dashboard: {
      welcome: 'مرحبا',
      dashboard: 'لوحة التحكم',
      tickets: 'التذاكر',
      customers: 'العملاء',
      technicians: 'الفنيون',
      inventory: 'المخزون',
      reports: 'التقارير',
      settings: 'الإعدادات',
      management: 'الإدارة',
      profile: 'الملف الشخصي',
      subscriptions: 'الاشتراكات',
      vehicles: 'المركبات',
      visits: 'الزيارات',
      payments: 'المدفوعات',
      notifications: 'الإشعارات',
      myAccount: 'حسابي',
      serviceHistory: 'سجل الخدمة',
      upcomingVisits: 'الزيارات القادمة',
      recentActivity: 'النشاط الأخير',
      statistics: 'الإحصائيات',
      overview: 'نظرة عامة',
    },
    ticket: {
      title: 'العنوان',
      status: 'الحالة',
      priority: 'الأولوية',
      description: 'الوصف',
      assignedTo: 'مسند إلى',
      createdAt: 'تاريخ الإنشاء',
      updatedAt: 'تاريخ التحديث',
      open: 'مفتوح',
      inProgress: 'قيد التنفيذ',
      resolved: 'محلول',
      closed: 'مغلق',
      low: 'منخفض',
      medium: 'متوسط',
      high: 'عالي',
      urgent: 'عاجل',
    },
    customer: {
      name: 'الاسم',
      email: 'البريد الإلكتروني',
      phone: 'الهاتف',
      vehicles: 'المركبات',
      serviceHistory: 'سجل الخدمة',
      vipTier: 'مستوى VIP',
    },
    customerDashboard: {
      dashboard: 'لوحة التحكم',
      manageTickets: 'إدارة تذاكر الدعم والاشتراكات الخاصة بك',
      subscribeNow: 'اشترك الآن',
      getRegularMaintenance: 'احصل على صيانة منتظمة للسيارة مع CarDoc أو AutoDoc',
      subscribeWeekly: 'اشترك في فحوصات دقيقة أسبوعية أو نصف أسبوعية. وفر الآلاف من خلال التشخيص الصحيح.',
      carDocFor1Car: 'CarDoc لسيارة واحدة',
      autoDocFor2to3Cars: 'AutoDoc لـ 2-3 سيارات',
      exploreSubscriptions: 'استكشف الاشتراكات',
      viewMySubscription: 'عرض اشتراكي',
      viewSubscriptionVisits: 'عرض الاشتراك والزيارات',
      myTickets: 'تذاكري',
      noTicketsYet: 'لا توجد تذاكر دعم بعد',
      createFirstTicket: 'أنشئ أول تذكرة للحصول على المساعدة من الفنيين',
      createTicket: 'إنشاء تذكرة',
      serviceHistory: 'سجل الخدمة',
      viewAllHistory: 'عرض كل السجل',
      myInvoices: 'فواتيري',
      viewAllInvoices: 'عرض كل الفواتير',
      customizeDashboard: 'تخصيص لوحة التحكم',
      switchToLightMode: 'التبديل إلى الوضع الفاتح',
      switchToDarkMode: 'التبديل إلى الوضع الداكن',
      newTicket: 'تذكرة دعم جديدة',
      ticketTitle: 'عنوان التذكرة',
      briefDescription: 'وصف مختصر للمشكلة',
      vehicleInfo: 'معلومات السيارة',
      vehicleMake: 'ماركة السيارة',
      vehicleModel: 'موديل السيارة',
      makeExample: 'تويوتا، فورد، بي إم دبليو، إلخ.',
      modelExample: 'كامري، F-150، X5، إلخ.',
      vehicleYear: 'سنة الصنع',
      serviceType: 'نوع الخدمة',
      serviceExample: 'تغيير زيت، إصلاح فرامل، إلخ.',
      problemDescription: 'وصف المشكلة',
      describeProblem: 'صف المشكلة بالتفصيل...',
      attachments: 'المرفقات (اختياري)',
      dragAndDrop: 'اسحب الملفات وأفلتها هنا، أو انقر للاختيار',
      clickToUpload: 'انقر للرفع',
      creating: 'جاري الإنشاء...',
      cancel: 'إلغاء',
      invoiceDetails: 'تفاصيل الفاتورة',
      ticketDetails: 'تفاصيل التذكرة',
      vehicle: 'السيارة',
      year: 'السنة',
      technician: 'الفني',
      notAssignedYet: 'لم يتم التعيين بعد',
      estimatedCost: 'التكلفة المقدرة',
      paymentStatus: 'حالة الدفع',
      messages: 'الرسائل',
      typeMessage: 'اكتب رسالتك...',
      send: 'إرسال',
      sending: 'جاري الإرسال...',
      close: 'إغلاق',
      paid: 'مدفوع',
      pending: 'قيد الانتظار',
      unpaid: 'غير مدفوع',
      open: 'مفتوحة',
      inProgress: 'قيد التنفيذ',
      awaitingPayment: 'في انتظار الدفع',
      resolved: 'تم الحل',
      closed: 'مغلقة',
    },
    subscription: {
      plans: 'خطط الاشتراك',
      carDoc: 'كاردوك',
      autoDoc: 'أوتودوك',
      weekly: 'أسبوعي',
      biWeekly: 'نصف أسبوعي',
      perMonth: 'شهرياً',
      subscribe: 'اشترك الآن',
      mostPopular: 'الأكثر شعبية',
      bestValue: 'أفضل قيمة',
      includes: 'يشمل',
      inspection: 'فحص',
      report: 'تقرير مفصل',
      support: 'دعم ذو أولوية',
      warranty: 'ضمان الخدمة',
      discount: 'خصم على الإصلاحات',
      active: 'نشط',
      expired: 'منتهي',
      canceled: 'ملغي',
      renewOn: 'يتجدد في',
      expiresOn: 'ينتهي في',
      canceledOn: 'ألغي في',
      chooseYourPlan: 'اختر خطة العناية بسيارتك',
      subscribeToCarDoc: 'اشترك في',
      andLetExperts: 'ودع فنيينا الخبراء يحافظون على سيارتك بصحة مثالية',
      monthly: 'شهرياً',
      yearly: 'سنوياً',
      save10: 'وفر 10%',
      oneCar: 'سيارة واحدة',
      twoCars: '2-3 سيارات',
      premium: 'بريميوم',
      xPerWeek: 'مرة/أسبوع',
      visits: 'زيارات',
      visitsPerCar: 'زيارات/سيارة',
      visitsMo: 'زيارات/شهر',
      oneVehicle: 'مركبة واحدة • مرة أو مرتين أسبوعياً',
      complete12System: 'فحص كامل لـ 12 نظام',
      reportsTracking: 'تقارير وتتبع التكاليف',
      support24_7: 'دعم 24/7',
      upTo3Vehicles: 'حتى 3 مركبات',
      priorityScheduling: 'جدولة ذات أولوية',
      advancedDiagnostics: 'تشخيص متقدم',
      fleetDashboard: 'لوحة الأسطول ودعم VIP',
      yearlySave: 'سنوياً: وفر 10%',
      getCarDoc: 'احصل على كاردوك',
      getAutoDoc: 'احصل على أوتودوك',
      howItWorks: 'كيف يعمل كاردوك وأوتودوك',
      subscribeStep: 'اشترك',
      subscribeStepDesc: 'اختر خطتك وحدد موعد زيارتك الأولى',
      weVisitYou: 'نزورك',
      weVisitYouDesc: 'يقوم فنينا بإجراء فحص دقيق كامل في موقعك',
      getReport: 'احصل على التقرير',
      getReportDesc: 'استلم النتائج والتوصيات التفصيلية فوراً',
      addVehicles: 'أضف مركباتك',
      selected: 'المحدد',
      vehicle: 'مركبة',
      makePlaceholder: 'تويوتا، بي إم دبليو، إلخ',
      modelPlaceholder: 'كامري، X5، إلخ',
      optional: 'اختياري',
      addAnotherVehicle: 'أضف مركبة أخرى',
      backToPlans: 'العودة للخطط',
      activating: 'جاري التفعيل...',
      activateSubscription: 'تفعيل الاشتراك',
      selectSubscription: 'اختر الاشتراك المناسب لاحتياجاتك',
      carDocPlans: 'خطط كاردوك (مركبة واحدة)',
      autoDocPlans: 'خطط أوتودوك (2-3 مركبات)',
      carOnly: 'سيارة واحدة فقط',
      perYear: '/سنة',
      selectPlan: 'اختر الخطة',
      selectPremiumPlan: 'اختر الخطة المميزة',
      support24_7Included: 'دعم 24/7 مشمول',
    },
    payment: {
      amount: 'المبلغ',
      date: 'التاريخ',
      method: 'طريقة الدفع',
      status: 'الحالة',
      paid: 'مدفوع',
      pending: 'قيد الانتظار',
      failed: 'فشل',
      cash: 'نقدي',
      card: 'بطاقة',
      bankTransfer: 'تحويل بنكي',
      receipt: 'إيصال',
      invoice: 'فاتورة',
      total: 'الإجمالي',
      subtotal: 'المجموع الفرعي',
      tax: 'الضريبة',
      discount: 'الخصم',
    },
    vehicle: {
      make: 'الصانع',
      model: 'الطراز',
      year: 'السنة',
      vin: 'رقم الهيكل',
      plateNumber: 'رقم اللوحة',
      mileage: 'المسافة المقطوعة',
      color: 'اللون',
      fuelType: 'نوع الوقود',
      transmission: 'ناقل الحركة',
      addVehicle: 'إضافة مركبة',
      editVehicle: 'تعديل المركبة',
      deleteVehicle: 'حذف المركبة',
    },
    visit: {
      scheduled: 'مجدول',
      completed: 'مكتمل',
      cancelled: 'ملغي',
      inProgress: 'قيد التنفيذ',
      scheduledFor: 'مجدول لـ',
      completedOn: 'اكتمل في',
      technician: 'الفني',
      notes: 'ملاحظات',
      report: 'التقرير',
      viewDetails: 'عرض التفاصيل',
      reschedule: 'إعادة الجدولة',
      cancel: 'إلغاء الزيارة',
    },
  },
};
